### PR TITLE
Add Webpack support

### PR DESCRIPTION
**Pull request by coxandrew**
**UPDATE**: Ok, this is ready for review!

This will allow you to do a simple `@import "vital"` in a Sass file when using Webpack after augmenting `includePaths` to your Webpack config file a la:

I created a simple, [sample demo](https://github.com/coxandrew/vital-webpack-demo) that just includes Babel and Lodash in addition to Vital to show how you could structure a Webpack project with Vital. Not sure if we want to point to it in the docs or just go with the simple instructions I added to the docs: 

screen shot 2017-05-05 at 2 10 20 pm

I also got this to work with `vue-genome`, but the Webpack config was a little more complex to get it to work with `vue`. Should I include instructions for that anywhere? It seems overly specific for the  "Getting Started" section right now.

Also unsure if this would be a version bump or not 🤷‍♂️ . LMK!

### CODE REVIEW

**Comment by coxandrew** [comment]
Nope! The resolver defaults to looking for `index.js`: https://webpack.js.org/configuration/resolve/#resolve-mainfiles

**Comment by bodytaing** [comment]
Nice job @coxandrew - Webpack support is awesome!

**Comment by coxandrew** [comment]
@fgrehm @bodytaing This is ready for review at your leisure.

kevin-bacon-finger-crossed

**Comment by chriswoodrich** [comment]
@coxandrew cc @bodytaing can you fix the conflicts and ship this?

**Comment by coxandrew** [comment]
Conflicts resolved. @bodytaing can you ship?

**Comment by bodytaing** [comment]
@coxandrew I can - shipping soon. 👍

**Pull request merged**
